times = ('SÃO PAULO', 'INTERNACIONAL', 'ATLETICO-MG', 'FLAMENGO', 'PALMEIRAS', 'GREMIO', 'FLUMINENSE', 'SANTOS', 'CORINTHIANS', 'ATLETICO-PR', 'CEARA', 'BRAGANTINO', 'ATLETICO-G0', 'SPORT', 'VASCO', 'FORTALEZA', 'BAHIA', 'GOIAS', 'CORIIBA', 'BOTAFOGO')
posicao = times.index('CORINTHIANS')
print('=-'*30)
print(f'Lista de times do Brasileirão: {times}')
print('=-'*30)
print(f'Os 5 primeiros são: {times[:5]}')
print('=-'*30)
print(f'Os 4 ultimos são: {times[-4:]}')
print('=-'*30)
print(f'Times em ordem alfabetica:', sorted(times))
print('=-'*30)
print(f'O Corinthians esta na {posicao+1} posição')